name: amplify_db_common_example
description: Demonstrates how to use the amplify_db_common plugin.
publish_to: "none"

environment:
  flutter: ">=3.10.0"
  sdk: '>=3.0.0'

dependencies:
  amplify_db_common: 0.3.5
  drift: 2.16.0
  flutter:
    sdk: flutter

dev_dependencies:
  amplify_lints: ^3.0.2
  drift_dev: 2.16.0
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
